spring:
  profiles:
    active: development
logging:
  level:
    root: INFO
    org.springframework.*: INFO
---
spring:
  profiles: development
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
server:
  port: 8080
